@startuml
left to right direction
title Classes

class User {
  pseudo
  password
  createdDate
  roleId
}

class Article {
    title 
    teaser 
    content 
    author 
    createdDate 
    updatedDate 
    top
}

class Comment {
    author
    content
    createdDate
    published
    flag
}

User "1" --- "0..*" Article
User "1" --- "0..*" Comment
Article "1" --- "0..*" Comment

@enduml