@startuml
left to right direction
actor "Admin" as ad
actor "Visiteur" as vi
actor "Abonné" as ab
rectangle Blog {
  usecase "Créer un article" as UC1
  usecase "Supprimer un article" as UC2
  usecase "Modicier un article" as UC3 
  usecase "Publier le commentaire" as UC4 
  usecase "Désignaler le commentiare" as UC5 
  usecase "Supprimer le commentaire" as UC6 
  usecase "Afficher la liste des articles" as UC11
  usecase "Consulter un article" as UC12
  usecase "Afficher la liste des commentaires" as UC13

  usecase "Signaler un commentaire" as UC21
  usecase "Ajouter un commentaire" as UC22
}
ad --> UC1
ad --> UC2
ad --> UC3
ad --> UC4
ad --> UC5
ad --> UC6
vi --> UC11
vi --> UC12
vi --> UC13
ab --> UC21
ab --> UC22
@enduml