  
name: PHP Composer + deploy
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Move to web
      run: cd ./html/

    - name: Composer update
      run: composer update

  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./html/docs/
        server-dir: ${{ secrets.FTP_DIR }}
        exclude: .git/*
          - .gitignore
          - ckfinder-config.php
          - composer.json
          - database.sql
          - docker-compose.yml
          - Dockerfile
          - environment.example.php
          - phpdoc.dist.xml
          - Procfile
          - environment.example.php
