name: PHP Composer
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Move to web
      run: cd ./html/

    - name: Composer update
      run: composer update
