on: push
name: 🚀 Deploy website by FTP on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./html/docs/
        server-dir: ${{ secrets.FTP_DIR }}
        exclude: .git/*
          - .gitignore
          - Dockerfile
          - docker-compose.yml
          - Procfile
          - ckfinder-config.php
          - composer.json
          - database.sql
          - environment.example.php
          - docs/*
          - phpdoc.dist.xml
          - docker-compose.yml